baseURL = 'https://nextjsvietnam.com'
languageCode = 'en-us'
title = 'Useful NodeJS Tricks, JavaScript Tips, Tricks and Best Practices'
theme = '2022'
ignoreFiles = ['\assets\node_modules\.*']
[params]
    name = "NextJSVietNam"
    description = "NodeJS Tricks, JavaScript Tips to Make You a Better Programmer"
    keywords = "Nodejs Tricks, Javascript Tips"
    dateFormat = "2006-01-02 15:04:05"
    image = "/themes/2022/src/assets/images/logo.png"
    blog_pager = 10
    note_pager = 10
    article_pager = 10
    home_post_limit = 10
    GACode = "G-RWE4MLJYE6"
    FBPixel = "1760611910980690"
    BingCode = "0899226C2935AEF15F1F831A889431FA"
[taxonomies]
    category = "categories"
    tag = "tags"